[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

[rpc_endpoints]
monad-testnet = "${MONAD_TESTNET_RPC}"

[etherscan]
monad-testnet = { key = "${MONAD_ETHERSCAN_API_KEY}" }